### ISSUE TITLE
Set up Body

### ISSUE THREAD

**Issue by FriFeb** [FriFeb/homepage#16]
- [x] Switch to the `develop` branch 

- [x] Pull the changes

- [x] Create a new branch named `feature/body` 

- [x] Push it to the `origin`

- [x] Set up primary content 

    - [x] Create a `patch/content/primary` branch
    - [x] Add a primary content template
    - [x] Create an `assets` folder 
    - [x] Put there any Bulka’s avatar image
    - [x] Place the contact info items inside the `contact-info__block` elements
    - [x] Add the provided intro block
    - [x] Push the changes
    - [x] Create a new pull request into the `feature/body` branch
    - [x] Merge the PR #18 

- [x] Switch back to the `feature/body` branch

- [x] Pull changes

- [x] Set up  secondary content

    - [x] Create `patch/content/secondary branch`
    - [x] Add a skills block
    - [x] Add an experience block
    - [x] Add some experiences
    - [x] Add additional info
    - [x] Push the changes
    - [x] Create a new pull request into the `feature/body` branch
    - [x] Merge the PR #21 

- [x] Switch back to the `feature/body` branch 

- [x] Pull the changes

- [x] #22

- [x] Create a new pull request into the `develop`

- [x] Merge the PR #23
